---
- name: "Install rsyslog from {{ ansible_distribution_release }} repository"
  apt:
    name: rsyslog
    state: latest
    default_release: "{{ ansible_distribution_release }}"
    update_cache: yes

- name: "Install OpenIO puppet module"
  apt:
    name: puppet-module-openio-openiosds
    update_cache: yes
...
