---
- name: Check if OS is supported for OpenIO SDS installation
  fail:
    msg: "{{ ansible_distribution }} operating system not supported."
  when: ansible_distribution != 'Debian'
        and ansible_distribution != 'Ubuntu'
        and ansible_distribution != 'RedHat'
        and ansible_distribution != 'Raspbian'
        and ansible_distribution != 'CentOS'

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include: sysctl.yml

- name: "Generate a Puppet manifest for namespace {{ openio_namespace }}"
  tags:
    - install
  template:
    src: openio.pp.j2
    dest: "{{ openio_puppet_manifest }}/{{ openio_namespace|lower }}.pp"
    owner: root
    group: root
    mode: 0644
    backup: true

- include: "{{ item }}"
  tags:
    - install
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: "Ensure directories are created"
  file:
    path: "{{ item.mountpoint }}/{{ openio_namespace }}"
    state: directory
    owner: root
    group: root
    mode: 0751
  with_items: "{{ openio_data_mounts }} + {{ openio_metadata_mounts }}"

- name: Provision with puppet
  include: provision.yml

- name: Bootstrap namespace
  tags:
    - bootstrap
  include: bootstrap.yml
  when: not openio_provision_only
...
